version: "3"

services:
    nginx:
        image: nginx:1-alpine
        container_name: nginx
        working_dir: /application
        volumes:
            - .:/application
            - /application/vendor
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/nginx/log/:/var/log/nginx/
        env_file:
            - .env
        ports:
            - "80:80"
        depends_on:
          - php
          - mongodb

    php:
        build: .docker/php-fpm
        container_name: php
        working_dir: /application
        volumes:
            - ~/.ssh/:/root/.ssh/
            - .:/application
            # Do not mount
            - /application/node_modules
            - ./.docker/php-fpm/custom.ini:/etc/php/7.2/fpm/conf.d/custom.ini
            - ./.docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        env_file:
            - .env
        tty: true

    mongodb:
        build: .docker/mongodb
        container_name: mongodb
        volumes:
            - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
            - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./.docker/mongodb/data/db/:/data/db/
            - ./.docker/mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - "27017:27017"

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - 8081:8081
        volumes:
            - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
        depends_on:
            - mongodb
